apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-core-pv
  namespace: amazon-recomendation-system
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/lantum/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-core-pvc
  namespace: amazon-recomendation-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
