apiVersion: v1
kind: Service
metadata:
  name: recomendation-service-service
  namespace: amazon-recomendation-system
spec:
  selector:
    app: recomendation-service-pod
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  